language: python
sudo: false
python:
  - 2.7_with_system_site_packages
  - 3.4
addons:
  apt:
    packages:
    - python-qt4
    - python-qt4-dev
    - python-qt4-gl
    - python-pip
    - python-numpy
    - python-wxtools
    - ccache
    - cmake
env:
  - ETS_TOOLKIT=qt4
  - ETS_TOOLKIT=null
  - ETS_TOOLKIT=wx
matrix:
  allow_failures:
    - env: ETS_TOOLKIT=wx
cache:
  directories:
    - $HOME/.cache
    - $HOME/.ccache
before_install:
  - ccache -s
  - pip install --upgrade pip
  - export PATH=/usr/lib/ccache:${PATH}
  - if [[ ${TRAVIS_PYTHON_VERSION} == "3.4" && ${ETS_TOOLKIT} == "qt4" ]]; then ./build_pyside_wheel.sh; fi
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - pip install -r travis-ci-requirements.txt
  - python setup.py develop
before_script:
  - mkdir testrun
  - cp .coveragerc testrun/
  - cd testrun
script:
  - coverage run -m nose.core -v traitsui.tests
  - if [[ ${ETS_TOOLKIT} == "qt4" ]]; then coverage run -a -m nose.core -v traitsui.qt4.tests; fi
after_success:
  - pip install codecov
  - codecov
