language: generic
sudo: false
matrix:
  include:
    - env: RUNTIME=2.7 TOOLKITS="null pyqt pyside"
    - env: RUNTIME=3.5 TOOLKITS="null pyqt"
    - env: RUNTIME=3.5 TOOLKITS="pyqt5"
    - os: osx
      env: RUNTIME=2.7 TOOLKITS="null pyside"
    - os: osx
      env: RUNTIME=3.5 TOOLKITS="null pyqt"
    - env: RUNTIME=2.7 TOOLKITS="wx"
    - os: osx
      env: RUNTIME=2.7 TOOLKITS="pyqt wx"
  allow_failures:
    - env: RUNTIME=2.7 TOOLKITS="wx"
    - env: RUNTIME=3.5 TOOLKITS="pyqt5"
    - os: osx
      env: RUNTIME=2.7 TOOLKITS="pyqt wx"
  fast_finish: true
cache:
  directories:
    - $HOME/.cache
before_install:
  - export DISPLAY=:99.0
  - if [[ ${TRAVIS_OS_NAME} == "linux" ]] ; then sh -e /etc/init.d/xvfb start ; fi
install:
  - ./travis_ci_bootstrap_edm.sh
  - for toolkit in ${TOOLKITS}; do edm run -- invoke install --runtime=${RUNTIME} --toolkit=${toolkit}; done
script:
  - for toolkit in ${TOOLKITS}; do edm run -- invoke test --runtime=${RUNTIME} --toolkit=${toolkit}; done
after_success:
  - edm run -- coverage combine
  - edm run -- pip install codecov
  - edm run -- codecov
